services:
  postgres:
    image: postgres:15-alpine
    container_name: messaging-app-postgres-dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication
    ports:
      - '5433:5432'
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user ']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-dev-data:
